name: fancy_cart
description: cart package for flutter which is easy to use and support all features, you can use it in your app to make it more fancy
version: 0.0.1
homepage: https://github.com/YousefSalahKassem/fancy_cart

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_test: ^1.0.1
  # State Management
  flutter_riverpod: ^1.0.4

  # Depend
  equatable: ^2.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: